# -*- coding: utf-8 -*-
"""scikitlearnknn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12UAIYlWOVOP5IdKwusPvH0hdSMqLiZW6

To choose K value plot the K vs accuracy graph, you will get a convex curv, i.e error will initially be high and then reach minimum and starts to increase again. k value at which you have minimum error is the best k value
"""

# getting our data playground ready
from sklearn import datasets
# getting KNN related artillery ready
from sklearn import neighbors

iris =  datasets.load_iris()
# the dataset is loaded as a dictionary of key-value pairs
# the relevant attributes:

from sklearn.model_selection import train_test_split
X,y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 42)

# create the model
knn_model = neighbors.KNeighborsClassifier(n_neighbors=5)

# fit the model
knn_model.fit(X_train,y_train)

# model predictions
predictions = knn_model.predict(X_test)
prob_predictions = knn_model.predict_proba(X_test)
predictions = [iris.target_names[i] for i in predictions]